/*
 * SPDX-License-Identifier: Apache-2.0
 */

// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod schematas {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum AdminAuditLogOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AdminAuditLog<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AdminAuditLog<'a> {
  type Inner = AdminAuditLog<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> AdminAuditLog<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_USERNAME: flatbuffers::VOffsetT = 6;
  pub const VT_ACTION: flatbuffers::VOffsetT = 8;
  pub const VT_DETAILS: flatbuffers::VOffsetT = 10;
  pub const VT_TS: flatbuffers::VOffsetT = 12;
  pub const VT_TS_UNIX_MS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    AdminAuditLog { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args AdminAuditLogArgs<'args>
  ) -> flatbuffers::WIPOffset<AdminAuditLog<'bldr>> {
    let mut builder = AdminAuditLogBuilder::new(_fbb);
    builder.add_ts_unix_ms(args.ts_unix_ms);
    builder.add_id(args.id);
    if let Some(x) = args.ts { builder.add_ts(x); }
    if let Some(x) = args.details { builder.add_details(x); }
    if let Some(x) = args.action { builder.add_action(x); }
    if let Some(x) = args.username { builder.add_username(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(AdminAuditLog::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn username(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AdminAuditLog::VT_USERNAME, None)}
  }
  #[inline]
  pub fn action(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AdminAuditLog::VT_ACTION, None)}
  }
  #[inline]
  pub fn details(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AdminAuditLog::VT_DETAILS, None)}
  }
  #[inline]
  pub fn ts(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(AdminAuditLog::VT_TS, None)}
  }
  #[inline]
  pub fn ts_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(AdminAuditLog::VT_TS_UNIX_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for AdminAuditLog<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("username", Self::VT_USERNAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("action", Self::VT_ACTION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("details", Self::VT_DETAILS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("ts", Self::VT_TS, false)?
     .visit_field::<i64>("ts_unix_ms", Self::VT_TS_UNIX_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct AdminAuditLogArgs<'a> {
    pub id: i64,
    pub username: Option<flatbuffers::WIPOffset<&'a str>>,
    pub action: Option<flatbuffers::WIPOffset<&'a str>>,
    pub details: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts_unix_ms: i64,
}
impl<'a> Default for AdminAuditLogArgs<'a> {
  #[inline]
  fn default() -> Self {
    AdminAuditLogArgs {
      id: 0,
      username: None,
      action: None,
      details: None,
      ts: None,
      ts_unix_ms: 0,
    }
  }
}

pub struct AdminAuditLogBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AdminAuditLogBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: i64) {
    self.fbb_.push_slot::<i64>(AdminAuditLog::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_username(&mut self, username: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdminAuditLog::VT_USERNAME, username);
  }
  #[inline]
  pub fn add_action(&mut self, action: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdminAuditLog::VT_ACTION, action);
  }
  #[inline]
  pub fn add_details(&mut self, details: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdminAuditLog::VT_DETAILS, details);
  }
  #[inline]
  pub fn add_ts(&mut self, ts: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdminAuditLog::VT_TS, ts);
  }
  #[inline]
  pub fn add_ts_unix_ms(&mut self, ts_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(AdminAuditLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AdminAuditLogBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AdminAuditLogBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AdminAuditLog<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for AdminAuditLog<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("AdminAuditLog");
      ds.field("id", &self.id());
      ds.field("username", &self.username());
      ds.field("action", &self.action());
      ds.field("details", &self.details());
      ds.field("ts", &self.ts());
      ds.field("ts_unix_ms", &self.ts_unix_ms());
      ds.finish()
  }
}
pub enum AdminAuditLogListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AdminAuditLogList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for AdminAuditLogList<'a> {
  type Inner = AdminAuditLogList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> AdminAuditLogList<'a> {
  pub const VT_LOGS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    AdminAuditLogList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args AdminAuditLogListArgs<'args>
  ) -> flatbuffers::WIPOffset<AdminAuditLogList<'bldr>> {
    let mut builder = AdminAuditLogListBuilder::new(_fbb);
    if let Some(x) = args.logs { builder.add_logs(x); }
    builder.finish()
  }


  #[inline]
  pub fn logs(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AdminAuditLog<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AdminAuditLog>>>>(AdminAuditLogList::VT_LOGS, None)}
  }
}

impl flatbuffers::Verifiable for AdminAuditLogList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<AdminAuditLog>>>>("logs", Self::VT_LOGS, false)?
     .finish();
    Ok(())
  }
}
pub struct AdminAuditLogListArgs<'a> {
    pub logs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AdminAuditLog<'a>>>>>,
}
impl<'a> Default for AdminAuditLogListArgs<'a> {
  #[inline]
  fn default() -> Self {
    AdminAuditLogListArgs {
      logs: None,
    }
  }
}

pub struct AdminAuditLogListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> AdminAuditLogListBuilder<'a, 'b> {
  #[inline]
  pub fn add_logs(&mut self, logs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<AdminAuditLog<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(AdminAuditLogList::VT_LOGS, logs);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> AdminAuditLogListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    AdminAuditLogListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<AdminAuditLogList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for AdminAuditLogList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("AdminAuditLogList");
      ds.field("logs", &self.logs());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `AdminAuditLogList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_admin_audit_log_list_unchecked`.
pub fn root_as_admin_audit_log_list(buf: &[u8]) -> Result<AdminAuditLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<AdminAuditLogList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `AdminAuditLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_admin_audit_log_list_unchecked`.
pub fn size_prefixed_root_as_admin_audit_log_list(buf: &[u8]) -> Result<AdminAuditLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<AdminAuditLogList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `AdminAuditLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_admin_audit_log_list_unchecked`.
pub fn root_as_admin_audit_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<AdminAuditLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<AdminAuditLogList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `AdminAuditLogList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_admin_audit_log_list_unchecked`.
pub fn size_prefixed_root_as_admin_audit_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<AdminAuditLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<AdminAuditLogList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a AdminAuditLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `AdminAuditLogList`.
pub unsafe fn root_as_admin_audit_log_list_unchecked(buf: &[u8]) -> AdminAuditLogList {
  flatbuffers::root_unchecked::<AdminAuditLogList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed AdminAuditLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `AdminAuditLogList`.
pub unsafe fn size_prefixed_root_as_admin_audit_log_list_unchecked(buf: &[u8]) -> AdminAuditLogList {
  flatbuffers::size_prefixed_root_unchecked::<AdminAuditLogList>(buf)
}
#[inline]
pub fn finish_admin_audit_log_list_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<AdminAuditLogList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_admin_audit_log_list_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<AdminAuditLogList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schematas

