/*
 * SPDX-License-Identifier: Apache-2.0
 */

// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod schematas {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum DLQEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DLQEntry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DLQEntry<'a> {
  type Inner = DLQEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DLQEntry<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_PACKAGE_ID: flatbuffers::VOffsetT = 6;
  pub const VT_PAYLOAD: flatbuffers::VOffsetT = 8;
  pub const VT_ERROR_CODE: flatbuffers::VOffsetT = 10;
  pub const VT_ERROR_MESSAGE: flatbuffers::VOffsetT = 12;
  pub const VT_FAILED_AT: flatbuffers::VOffsetT = 14;
  pub const VT_FAILED_AT_UNIX_MS: flatbuffers::VOffsetT = 16;
  pub const VT_RESOLVED: flatbuffers::VOffsetT = 18;
  pub const VT_RESOLVED_AT: flatbuffers::VOffsetT = 20;
  pub const VT_RESOLVED_AT_UNIX_MS: flatbuffers::VOffsetT = 22;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DLQEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DLQEntryArgs<'args>
  ) -> flatbuffers::WIPOffset<DLQEntry<'bldr>> {
    let mut builder = DLQEntryBuilder::new(_fbb);
    builder.add_resolved_at_unix_ms(args.resolved_at_unix_ms);
    builder.add_failed_at_unix_ms(args.failed_at_unix_ms);
    if let Some(x) = args.resolved_at { builder.add_resolved_at(x); }
    if let Some(x) = args.failed_at { builder.add_failed_at(x); }
    if let Some(x) = args.error_message { builder.add_error_message(x); }
    if let Some(x) = args.error_code { builder.add_error_code(x); }
    if let Some(x) = args.payload { builder.add_payload(x); }
    if let Some(x) = args.package_id { builder.add_package_id(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.add_resolved(args.resolved);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_ID, None)}
  }
  #[inline]
  pub fn package_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_PACKAGE_ID, None)}
  }
  #[inline]
  pub fn payload(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_PAYLOAD, None)}
  }
  #[inline]
  pub fn error_code(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_ERROR_CODE, None)}
  }
  #[inline]
  pub fn error_message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_ERROR_MESSAGE, None)}
  }
  #[inline]
  pub fn failed_at(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_FAILED_AT, None)}
  }
  #[inline]
  pub fn failed_at_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(DLQEntry::VT_FAILED_AT_UNIX_MS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn resolved(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(DLQEntry::VT_RESOLVED, Some(false)).unwrap()}
  }
  #[inline]
  pub fn resolved_at(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DLQEntry::VT_RESOLVED_AT, None)}
  }
  #[inline]
  pub fn resolved_at_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(DLQEntry::VT_RESOLVED_AT_UNIX_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for DLQEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("package_id", Self::VT_PACKAGE_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("payload", Self::VT_PAYLOAD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("error_code", Self::VT_ERROR_CODE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("error_message", Self::VT_ERROR_MESSAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("failed_at", Self::VT_FAILED_AT, false)?
     .visit_field::<i64>("failed_at_unix_ms", Self::VT_FAILED_AT_UNIX_MS, false)?
     .visit_field::<bool>("resolved", Self::VT_RESOLVED, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("resolved_at", Self::VT_RESOLVED_AT, false)?
     .visit_field::<i64>("resolved_at_unix_ms", Self::VT_RESOLVED_AT_UNIX_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct DLQEntryArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub package_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub payload: Option<flatbuffers::WIPOffset<&'a str>>,
    pub error_code: Option<flatbuffers::WIPOffset<&'a str>>,
    pub error_message: Option<flatbuffers::WIPOffset<&'a str>>,
    pub failed_at: Option<flatbuffers::WIPOffset<&'a str>>,
    pub failed_at_unix_ms: i64,
    pub resolved: bool,
    pub resolved_at: Option<flatbuffers::WIPOffset<&'a str>>,
    pub resolved_at_unix_ms: i64,
}
impl<'a> Default for DLQEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    DLQEntryArgs {
      id: None,
      package_id: None,
      payload: None,
      error_code: None,
      error_message: None,
      failed_at: None,
      failed_at_unix_ms: 0,
      resolved: false,
      resolved_at: None,
      resolved_at_unix_ms: 0,
    }
  }
}

pub struct DLQEntryBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DLQEntryBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_ID, id);
  }
  #[inline]
  pub fn add_package_id(&mut self, package_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_PACKAGE_ID, package_id);
  }
  #[inline]
  pub fn add_payload(&mut self, payload: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_PAYLOAD, payload);
  }
  #[inline]
  pub fn add_error_code(&mut self, error_code: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_ERROR_CODE, error_code);
  }
  #[inline]
  pub fn add_error_message(&mut self, error_message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_ERROR_MESSAGE, error_message);
  }
  #[inline]
  pub fn add_failed_at(&mut self, failed_at: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_FAILED_AT, failed_at);
  }
  #[inline]
  pub fn add_failed_at_unix_ms(&mut self, failed_at_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(DLQEntry::VT_FAILED_AT_UNIX_MS, failed_at_unix_ms, 0);
  }
  #[inline]
  pub fn add_resolved(&mut self, resolved: bool) {
    self.fbb_.push_slot::<bool>(DLQEntry::VT_RESOLVED, resolved, false);
  }
  #[inline]
  pub fn add_resolved_at(&mut self, resolved_at: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntry::VT_RESOLVED_AT, resolved_at);
  }
  #[inline]
  pub fn add_resolved_at_unix_ms(&mut self, resolved_at_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(DLQEntry::VT_RESOLVED_AT_UNIX_MS, resolved_at_unix_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DLQEntryBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DLQEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DLQEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DLQEntry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DLQEntry");
      ds.field("id", &self.id());
      ds.field("package_id", &self.package_id());
      ds.field("payload", &self.payload());
      ds.field("error_code", &self.error_code());
      ds.field("error_message", &self.error_message());
      ds.field("failed_at", &self.failed_at());
      ds.field("failed_at_unix_ms", &self.failed_at_unix_ms());
      ds.field("resolved", &self.resolved());
      ds.field("resolved_at", &self.resolved_at());
      ds.field("resolved_at_unix_ms", &self.resolved_at_unix_ms());
      ds.finish()
  }
}
pub enum DLQEntryListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DLQEntryList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DLQEntryList<'a> {
  type Inner = DLQEntryList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> DLQEntryList<'a> {
  pub const VT_ENTRIES: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DLQEntryList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args DLQEntryListArgs<'args>
  ) -> flatbuffers::WIPOffset<DLQEntryList<'bldr>> {
    let mut builder = DLQEntryListBuilder::new(_fbb);
    if let Some(x) = args.entries { builder.add_entries(x); }
    builder.finish()
  }


  #[inline]
  pub fn entries(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DLQEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DLQEntry>>>>(DLQEntryList::VT_ENTRIES, None)}
  }
}

impl flatbuffers::Verifiable for DLQEntryList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<DLQEntry>>>>("entries", Self::VT_ENTRIES, false)?
     .finish();
    Ok(())
  }
}
pub struct DLQEntryListArgs<'a> {
    pub entries: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<DLQEntry<'a>>>>>,
}
impl<'a> Default for DLQEntryListArgs<'a> {
  #[inline]
  fn default() -> Self {
    DLQEntryListArgs {
      entries: None,
    }
  }
}

pub struct DLQEntryListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> DLQEntryListBuilder<'a, 'b> {
  #[inline]
  pub fn add_entries(&mut self, entries: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<DLQEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DLQEntryList::VT_ENTRIES, entries);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> DLQEntryListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    DLQEntryListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DLQEntryList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DLQEntryList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DLQEntryList");
      ds.field("entries", &self.entries());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `DLQEntryList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dlqentry_list_unchecked`.
pub fn root_as_dlqentry_list(buf: &[u8]) -> Result<DLQEntryList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<DLQEntryList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `DLQEntryList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_dlqentry_list_unchecked`.
pub fn size_prefixed_root_as_dlqentry_list(buf: &[u8]) -> Result<DLQEntryList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<DLQEntryList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `DLQEntryList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dlqentry_list_unchecked`.
pub fn root_as_dlqentry_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DLQEntryList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<DLQEntryList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `DLQEntryList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_dlqentry_list_unchecked`.
pub fn size_prefixed_root_as_dlqentry_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<DLQEntryList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<DLQEntryList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a DLQEntryList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `DLQEntryList`.
pub unsafe fn root_as_dlqentry_list_unchecked(buf: &[u8]) -> DLQEntryList {
  flatbuffers::root_unchecked::<DLQEntryList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed DLQEntryList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `DLQEntryList`.
pub unsafe fn size_prefixed_root_as_dlqentry_list_unchecked(buf: &[u8]) -> DLQEntryList {
  flatbuffers::size_prefixed_root_unchecked::<DLQEntryList>(buf)
}
#[inline]
pub fn finish_dlqentry_list_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<DLQEntryList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_dlqentry_list_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<DLQEntryList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schematas

