/*
 * SPDX-License-Identifier: Apache-2.0
 */

// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod schematas {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum JobAuditLogOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct JobAuditLog<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for JobAuditLog<'a> {
  type Inner = JobAuditLog<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> JobAuditLog<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_RUN_ID: flatbuffers::VOffsetT = 6;
  pub const VT_COMPONENT: flatbuffers::VOffsetT = 8;
  pub const VT_MESSAGE: flatbuffers::VOffsetT = 10;
  pub const VT_TS: flatbuffers::VOffsetT = 12;
  pub const VT_TS_UNIX_MS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    JobAuditLog { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args JobAuditLogArgs<'args>
  ) -> flatbuffers::WIPOffset<JobAuditLog<'bldr>> {
    let mut builder = JobAuditLogBuilder::new(_fbb);
    builder.add_ts_unix_ms(args.ts_unix_ms);
    builder.add_run_id(args.run_id);
    builder.add_id(args.id);
    if let Some(x) = args.ts { builder.add_ts(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.component { builder.add_component(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(JobAuditLog::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn run_id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(JobAuditLog::VT_RUN_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn component(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(JobAuditLog::VT_COMPONENT, None)}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(JobAuditLog::VT_MESSAGE, None)}
  }
  #[inline]
  pub fn ts(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(JobAuditLog::VT_TS, None)}
  }
  #[inline]
  pub fn ts_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(JobAuditLog::VT_TS_UNIX_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for JobAuditLog<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("id", Self::VT_ID, false)?
     .visit_field::<i64>("run_id", Self::VT_RUN_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("component", Self::VT_COMPONENT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("ts", Self::VT_TS, false)?
     .visit_field::<i64>("ts_unix_ms", Self::VT_TS_UNIX_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct JobAuditLogArgs<'a> {
    pub id: i64,
    pub run_id: i64,
    pub component: Option<flatbuffers::WIPOffset<&'a str>>,
    pub message: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts_unix_ms: i64,
}
impl<'a> Default for JobAuditLogArgs<'a> {
  #[inline]
  fn default() -> Self {
    JobAuditLogArgs {
      id: 0,
      run_id: 0,
      component: None,
      message: None,
      ts: None,
      ts_unix_ms: 0,
    }
  }
}

pub struct JobAuditLogBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> JobAuditLogBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: i64) {
    self.fbb_.push_slot::<i64>(JobAuditLog::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_run_id(&mut self, run_id: i64) {
    self.fbb_.push_slot::<i64>(JobAuditLog::VT_RUN_ID, run_id, 0);
  }
  #[inline]
  pub fn add_component(&mut self, component: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(JobAuditLog::VT_COMPONENT, component);
  }
  #[inline]
  pub fn add_message(&mut self, message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(JobAuditLog::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_ts(&mut self, ts: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(JobAuditLog::VT_TS, ts);
  }
  #[inline]
  pub fn add_ts_unix_ms(&mut self, ts_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(JobAuditLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> JobAuditLogBuilder<'a, 'b> {
    let start = _fbb.start_table();
    JobAuditLogBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<JobAuditLog<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for JobAuditLog<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("JobAuditLog");
      ds.field("id", &self.id());
      ds.field("run_id", &self.run_id());
      ds.field("component", &self.component());
      ds.field("message", &self.message());
      ds.field("ts", &self.ts());
      ds.field("ts_unix_ms", &self.ts_unix_ms());
      ds.finish()
  }
}
pub enum JobAuditLogListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct JobAuditLogList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for JobAuditLogList<'a> {
  type Inner = JobAuditLogList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> JobAuditLogList<'a> {
  pub const VT_LOGS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    JobAuditLogList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args JobAuditLogListArgs<'args>
  ) -> flatbuffers::WIPOffset<JobAuditLogList<'bldr>> {
    let mut builder = JobAuditLogListBuilder::new(_fbb);
    if let Some(x) = args.logs { builder.add_logs(x); }
    builder.finish()
  }


  #[inline]
  pub fn logs(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<JobAuditLog<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<JobAuditLog>>>>(JobAuditLogList::VT_LOGS, None)}
  }
}

impl flatbuffers::Verifiable for JobAuditLogList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<JobAuditLog>>>>("logs", Self::VT_LOGS, false)?
     .finish();
    Ok(())
  }
}
pub struct JobAuditLogListArgs<'a> {
    pub logs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<JobAuditLog<'a>>>>>,
}
impl<'a> Default for JobAuditLogListArgs<'a> {
  #[inline]
  fn default() -> Self {
    JobAuditLogListArgs {
      logs: None,
    }
  }
}

pub struct JobAuditLogListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> JobAuditLogListBuilder<'a, 'b> {
  #[inline]
  pub fn add_logs(&mut self, logs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<JobAuditLog<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(JobAuditLogList::VT_LOGS, logs);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> JobAuditLogListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    JobAuditLogListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<JobAuditLogList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for JobAuditLogList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("JobAuditLogList");
      ds.field("logs", &self.logs());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `JobAuditLogList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_job_audit_log_list_unchecked`.
pub fn root_as_job_audit_log_list(buf: &[u8]) -> Result<JobAuditLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<JobAuditLogList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `JobAuditLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_job_audit_log_list_unchecked`.
pub fn size_prefixed_root_as_job_audit_log_list(buf: &[u8]) -> Result<JobAuditLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<JobAuditLogList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `JobAuditLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_job_audit_log_list_unchecked`.
pub fn root_as_job_audit_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JobAuditLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<JobAuditLogList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `JobAuditLogList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_job_audit_log_list_unchecked`.
pub fn size_prefixed_root_as_job_audit_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<JobAuditLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<JobAuditLogList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a JobAuditLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `JobAuditLogList`.
pub unsafe fn root_as_job_audit_log_list_unchecked(buf: &[u8]) -> JobAuditLogList {
  flatbuffers::root_unchecked::<JobAuditLogList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed JobAuditLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `JobAuditLogList`.
pub unsafe fn size_prefixed_root_as_job_audit_log_list_unchecked(buf: &[u8]) -> JobAuditLogList {
  flatbuffers::size_prefixed_root_unchecked::<JobAuditLogList>(buf)
}
#[inline]
pub fn finish_job_audit_log_list_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<JobAuditLogList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_job_audit_log_list_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<JobAuditLogList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schematas

