// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod schematas {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum SystemLogOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SystemLog<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SystemLog<'a> {
  type Inner = SystemLog<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SystemLog<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_LEVEL: flatbuffers::VOffsetT = 6;
  pub const VT_COMPONENT: flatbuffers::VOffsetT = 8;
  pub const VT_MESSAGE: flatbuffers::VOffsetT = 10;
  pub const VT_TS: flatbuffers::VOffsetT = 12;
  pub const VT_TS_UNIX_MS: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SystemLog { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args SystemLogArgs<'args>
  ) -> flatbuffers::WIPOffset<SystemLog<'bldr>> {
    let mut builder = SystemLogBuilder::new(_fbb);
    builder.add_ts_unix_ms(args.ts_unix_ms);
    builder.add_id(args.id);
    if let Some(x) = args.ts { builder.add_ts(x); }
    if let Some(x) = args.message { builder.add_message(x); }
    if let Some(x) = args.component { builder.add_component(x); }
    if let Some(x) = args.level { builder.add_level(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(SystemLog::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn level(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemLog::VT_LEVEL, None)}
  }
  #[inline]
  pub fn component(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemLog::VT_COMPONENT, None)}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemLog::VT_MESSAGE, None)}
  }
  #[inline]
  pub fn ts(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemLog::VT_TS, None)}
  }
  #[inline]
  pub fn ts_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(SystemLog::VT_TS_UNIX_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for SystemLog<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("level", Self::VT_LEVEL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("component", Self::VT_COMPONENT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("ts", Self::VT_TS, false)?
     .visit_field::<i64>("ts_unix_ms", Self::VT_TS_UNIX_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct SystemLogArgs<'a> {
    pub id: i64,
    pub level: Option<flatbuffers::WIPOffset<&'a str>>,
    pub component: Option<flatbuffers::WIPOffset<&'a str>>,
    pub message: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts: Option<flatbuffers::WIPOffset<&'a str>>,
    pub ts_unix_ms: i64,
}
impl<'a> Default for SystemLogArgs<'a> {
  #[inline]
  fn default() -> Self {
    SystemLogArgs {
      id: 0,
      level: None,
      component: None,
      message: None,
      ts: None,
      ts_unix_ms: 0,
    }
  }
}

pub struct SystemLogBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SystemLogBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: i64) {
    self.fbb_.push_slot::<i64>(SystemLog::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_level(&mut self, level: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemLog::VT_LEVEL, level);
  }
  #[inline]
  pub fn add_component(&mut self, component: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemLog::VT_COMPONENT, component);
  }
  #[inline]
  pub fn add_message(&mut self, message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemLog::VT_MESSAGE, message);
  }
  #[inline]
  pub fn add_ts(&mut self, ts: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemLog::VT_TS, ts);
  }
  #[inline]
  pub fn add_ts_unix_ms(&mut self, ts_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(SystemLog::VT_TS_UNIX_MS, ts_unix_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SystemLogBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SystemLogBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SystemLog<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SystemLog<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SystemLog");
      ds.field("id", &self.id());
      ds.field("level", &self.level());
      ds.field("component", &self.component());
      ds.field("message", &self.message());
      ds.field("ts", &self.ts());
      ds.field("ts_unix_ms", &self.ts_unix_ms());
      ds.finish()
  }
}
pub enum SystemLogListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SystemLogList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SystemLogList<'a> {
  type Inner = SystemLogList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> SystemLogList<'a> {
  pub const VT_LOGS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SystemLogList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args SystemLogListArgs<'args>
  ) -> flatbuffers::WIPOffset<SystemLogList<'bldr>> {
    let mut builder = SystemLogListBuilder::new(_fbb);
    if let Some(x) = args.logs { builder.add_logs(x); }
    builder.finish()
  }


  #[inline]
  pub fn logs(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SystemLog<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SystemLog>>>>(SystemLogList::VT_LOGS, None)}
  }
}

impl flatbuffers::Verifiable for SystemLogList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<SystemLog>>>>("logs", Self::VT_LOGS, false)?
     .finish();
    Ok(())
  }
}
pub struct SystemLogListArgs<'a> {
    pub logs: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<SystemLog<'a>>>>>,
}
impl<'a> Default for SystemLogListArgs<'a> {
  #[inline]
  fn default() -> Self {
    SystemLogListArgs {
      logs: None,
    }
  }
}

pub struct SystemLogListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> SystemLogListBuilder<'a, 'b> {
  #[inline]
  pub fn add_logs(&mut self, logs: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<SystemLog<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemLogList::VT_LOGS, logs);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> SystemLogListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    SystemLogListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SystemLogList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SystemLogList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SystemLogList");
      ds.field("logs", &self.logs());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `SystemLogList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_system_log_list_unchecked`.
pub fn root_as_system_log_list(buf: &[u8]) -> Result<SystemLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<SystemLogList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `SystemLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_system_log_list_unchecked`.
pub fn size_prefixed_root_as_system_log_list(buf: &[u8]) -> Result<SystemLogList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<SystemLogList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `SystemLogList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_system_log_list_unchecked`.
pub fn root_as_system_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SystemLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<SystemLogList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `SystemLogList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_system_log_list_unchecked`.
pub fn size_prefixed_root_as_system_log_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<SystemLogList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<SystemLogList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a SystemLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `SystemLogList`.
pub unsafe fn root_as_system_log_list_unchecked(buf: &[u8]) -> SystemLogList {
  flatbuffers::root_unchecked::<SystemLogList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed SystemLogList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `SystemLogList`.
pub unsafe fn size_prefixed_root_as_system_log_list_unchecked(buf: &[u8]) -> SystemLogList {
  flatbuffers::size_prefixed_root_unchecked::<SystemLogList>(buf)
}
#[inline]
pub fn finish_system_log_list_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<SystemLogList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_system_log_list_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<SystemLogList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schematas

