// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod schematas {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum TransformationErrorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TransformationError<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TransformationError<'a> {
  type Inner = TransformationError<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TransformationError<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_CORRELATION_ID: flatbuffers::VOffsetT = 6;
  pub const VT_TOPIC: flatbuffers::VOffsetT = 8;
  pub const VT_FAILED_FIELD: flatbuffers::VOffsetT = 10;
  pub const VT_RULE_NAME: flatbuffers::VOffsetT = 12;
  pub const VT_ERROR_MESSAGE: flatbuffers::VOffsetT = 14;
  pub const VT_CREATED_AT: flatbuffers::VOffsetT = 16;
  pub const VT_CREATED_AT_UNIX_MS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TransformationError { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TransformationErrorArgs<'args>
  ) -> flatbuffers::WIPOffset<TransformationError<'bldr>> {
    let mut builder = TransformationErrorBuilder::new(_fbb);
    builder.add_created_at_unix_ms(args.created_at_unix_ms);
    if let Some(x) = args.created_at { builder.add_created_at(x); }
    if let Some(x) = args.error_message { builder.add_error_message(x); }
    if let Some(x) = args.rule_name { builder.add_rule_name(x); }
    if let Some(x) = args.failed_field { builder.add_failed_field(x); }
    if let Some(x) = args.topic { builder.add_topic(x); }
    if let Some(x) = args.correlation_id { builder.add_correlation_id(x); }
    if let Some(x) = args.id { builder.add_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_ID, None)}
  }
  #[inline]
  pub fn correlation_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_CORRELATION_ID, None)}
  }
  #[inline]
  pub fn topic(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_TOPIC, None)}
  }
  #[inline]
  pub fn failed_field(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_FAILED_FIELD, None)}
  }
  #[inline]
  pub fn rule_name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_RULE_NAME, None)}
  }
  #[inline]
  pub fn error_message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_ERROR_MESSAGE, None)}
  }
  #[inline]
  pub fn created_at(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TransformationError::VT_CREATED_AT, None)}
  }
  #[inline]
  pub fn created_at_unix_ms(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(TransformationError::VT_CREATED_AT_UNIX_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TransformationError<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("correlation_id", Self::VT_CORRELATION_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("topic", Self::VT_TOPIC, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("failed_field", Self::VT_FAILED_FIELD, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("rule_name", Self::VT_RULE_NAME, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("error_message", Self::VT_ERROR_MESSAGE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("created_at", Self::VT_CREATED_AT, false)?
     .visit_field::<i64>("created_at_unix_ms", Self::VT_CREATED_AT_UNIX_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct TransformationErrorArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub correlation_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub topic: Option<flatbuffers::WIPOffset<&'a str>>,
    pub failed_field: Option<flatbuffers::WIPOffset<&'a str>>,
    pub rule_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub error_message: Option<flatbuffers::WIPOffset<&'a str>>,
    pub created_at: Option<flatbuffers::WIPOffset<&'a str>>,
    pub created_at_unix_ms: i64,
}
impl<'a> Default for TransformationErrorArgs<'a> {
  #[inline]
  fn default() -> Self {
    TransformationErrorArgs {
      id: None,
      correlation_id: None,
      topic: None,
      failed_field: None,
      rule_name: None,
      error_message: None,
      created_at: None,
      created_at_unix_ms: 0,
    }
  }
}

pub struct TransformationErrorBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TransformationErrorBuilder<'a, 'b> {
  #[inline]
  pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_ID, id);
  }
  #[inline]
  pub fn add_correlation_id(&mut self, correlation_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_CORRELATION_ID, correlation_id);
  }
  #[inline]
  pub fn add_topic(&mut self, topic: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_TOPIC, topic);
  }
  #[inline]
  pub fn add_failed_field(&mut self, failed_field: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_FAILED_FIELD, failed_field);
  }
  #[inline]
  pub fn add_rule_name(&mut self, rule_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_RULE_NAME, rule_name);
  }
  #[inline]
  pub fn add_error_message(&mut self, error_message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_ERROR_MESSAGE, error_message);
  }
  #[inline]
  pub fn add_created_at(&mut self, created_at: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationError::VT_CREATED_AT, created_at);
  }
  #[inline]
  pub fn add_created_at_unix_ms(&mut self, created_at_unix_ms: i64) {
    self.fbb_.push_slot::<i64>(TransformationError::VT_CREATED_AT_UNIX_MS, created_at_unix_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TransformationErrorBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TransformationErrorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TransformationError<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TransformationError<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TransformationError");
      ds.field("id", &self.id());
      ds.field("correlation_id", &self.correlation_id());
      ds.field("topic", &self.topic());
      ds.field("failed_field", &self.failed_field());
      ds.field("rule_name", &self.rule_name());
      ds.field("error_message", &self.error_message());
      ds.field("created_at", &self.created_at());
      ds.field("created_at_unix_ms", &self.created_at_unix_ms());
      ds.finish()
  }
}
pub enum TransformationErrorListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TransformationErrorList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TransformationErrorList<'a> {
  type Inner = TransformationErrorList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> TransformationErrorList<'a> {
  pub const VT_ERRORS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TransformationErrorList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args TransformationErrorListArgs<'args>
  ) -> flatbuffers::WIPOffset<TransformationErrorList<'bldr>> {
    let mut builder = TransformationErrorListBuilder::new(_fbb);
    if let Some(x) = args.errors { builder.add_errors(x); }
    builder.finish()
  }


  #[inline]
  pub fn errors(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TransformationError<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TransformationError>>>>(TransformationErrorList::VT_ERRORS, None)}
  }
}

impl flatbuffers::Verifiable for TransformationErrorList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<TransformationError>>>>("errors", Self::VT_ERRORS, false)?
     .finish();
    Ok(())
  }
}
pub struct TransformationErrorListArgs<'a> {
    pub errors: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TransformationError<'a>>>>>,
}
impl<'a> Default for TransformationErrorListArgs<'a> {
  #[inline]
  fn default() -> Self {
    TransformationErrorListArgs {
      errors: None,
    }
  }
}

pub struct TransformationErrorListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TransformationErrorListBuilder<'a, 'b> {
  #[inline]
  pub fn add_errors(&mut self, errors: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TransformationError<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TransformationErrorList::VT_ERRORS, errors);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TransformationErrorListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TransformationErrorListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TransformationErrorList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TransformationErrorList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TransformationErrorList");
      ds.field("errors", &self.errors());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `TransformationErrorList`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transformation_error_list_unchecked`.
pub fn root_as_transformation_error_list(buf: &[u8]) -> Result<TransformationErrorList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<TransformationErrorList>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TransformationErrorList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_transformation_error_list_unchecked`.
pub fn size_prefixed_root_as_transformation_error_list(buf: &[u8]) -> Result<TransformationErrorList, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<TransformationErrorList>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TransformationErrorList` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transformation_error_list_unchecked`.
pub fn root_as_transformation_error_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TransformationErrorList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<TransformationErrorList<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TransformationErrorList` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transformation_error_list_unchecked`.
pub fn size_prefixed_root_as_transformation_error_list_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<TransformationErrorList<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<TransformationErrorList<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TransformationErrorList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TransformationErrorList`.
pub unsafe fn root_as_transformation_error_list_unchecked(buf: &[u8]) -> TransformationErrorList {
  flatbuffers::root_unchecked::<TransformationErrorList>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TransformationErrorList and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TransformationErrorList`.
pub unsafe fn size_prefixed_root_as_transformation_error_list_unchecked(buf: &[u8]) -> TransformationErrorList {
  flatbuffers::size_prefixed_root_unchecked::<TransformationErrorList>(buf)
}
#[inline]
pub fn finish_transformation_error_list_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<TransformationErrorList<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_transformation_error_list_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<TransformationErrorList<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod schematas

