[supervisord]
nodaemon=true

[program:iam-server]
command=/app/bin/mitm-core-iam
autostart=true
autorestart=true
priority=10

[program:scheduler-server]
command=/app/bin/mitm-core-scheduler
autostart=true
autorestart=true
priority=20

[program:http-server]
command=/app/bin/mitm-core-http
autostart=true
autorestart=true
priority=30