[package]
name = "mitm-iam-server"
version = "1.0.1"
edition = "2024"
license = "Apache-2.0"
description = "MitM Identity and Access Management server (RBAC/ABAC) - core layer"
homepage = "https://github.com/Zheng-Bote/mitm-3"
repository = "https://github.com/Zheng-Bote/mitm-3/release/latest"
documentation = "https://github.com/Zheng-Bote/mitm-3/docs"
keywords = ["mitm-3", "core-layer", "iam-server"]

[dependencies]
mitm_common = { path = "../mitm_common" }
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "chrono"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
base64 = "0.22"
rand = "0.8"
subtle = "2.6"
